### ISSUE TITLE
Kubernetes 1.21+: Token-handling code assumes auto-created service account token secrets

### ISSUE THREAD

**Issue by liggitt** [superbrothers/kubectl-view-kubeconfig-plugin#53]
Sweeping token-scraping of auto-generated Kubernetes token secrets in preparation for Kubernetes 1.24 showed the following code locations assume auto-generated tokens will exist:

https://github.com/superbrothers/kubectl-view-serviceaccount-kubeconfig-plugin/blob/6bb716efb1aa13ba9ccdebcef7f2fa2532cc9458/pkg/cmd/view-serviceaccount-kubeconfig.go#L154-L182

That assumption is not universally correct.

In 1.21+, secret-based tokens are no longer used for mounting into pods (ephemeral time-limited tokens are), and the token controller can be turned off.

In 1.24+, secret-based tokens are no longer auto-created by default for new service accounts.

To reproduce, create a 1.24 Kubernetes cluster or a 1.21+ Kubernetes cluster with the token controller disabled.

Using ephemeral time-bound tokens is preferred in 1.21+ (see the [TokenRequest](https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/token-request-v1/) API) if possible.

If a secret-based token is still desired, one can be [created manually](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-a-service-account-api-token), but will not be referenced from the service account's .secrets list.

**Comment by superbrothers** [comment]
Thanks for the comment, I will look into changing this plugin to handle bound tokens.

**Comment by chandrakanth-gudavalli** [comment]
I think, inorder to find a Secret belonging to a ServiceAccount we need to search for all Secrets having the proper annotation.

**Comment by Ab-hishek** [comment]
Any update on this? I need a KUBECONFIG for a sa in 1.24 k8s version but not able to do it right now because of the limitation. Is there some short-term workaround available?

**Comment by superbrothers** [comment]
I have started to implement this feature, but it will take some time to provide it.

Below are the steps to get the kubeconfig file for the default serviceaccount of the default namespace. Please refer to it.

```
$ k config view --minify --flatten >kubeconfig.tmp
$ TOKEN="$(kubectl create token default -n default)"
$ KUBECONFIG=./kubeconfig.tmp kubectl config set-credentials default  --token="$TOKEN"
User "default" set.
$ KUBECONFIG=./kubeconfig.tmp kubectl config set-context --current --user default
Context "kind-kind" modified.
$ KUBECONFIG=./kubeconfig.tmp kubectl config view --flatten --minify >kubeconfig
$ rm kubeconfig.tmp
$ KUBECONFIG=./kubeconfig kubectl get po
Error from server (Forbidden): pods is forbidden: User "system:serviceaccount:default:default" cannot list resource "pods" in API group "" in the namespace "default"
```

**Comment by flavio** [comment]
@superbrothers could you tag a new release with this fix please? :pray:

**Comment by superbrothers** [comment]
I'll do it in this weekend.

**Comment by superbrothers** [comment]
I just released it, and once the PRs to krew-index are merged, you can install the new version with krew.

https://github.com/kubernetes-sigs/krew-index/pull/3075

If you cannot wait for the PRs to be merged, you can download the binary from the release page or install it with the following command:

```
kubectl krew uninstall view-serviceaccount-kubeconfig ||:
kubectl krew install --manifest <(curl -sL https://github.com/superbrothers/kubectl-view-serviceaccount-kubeconfig-plugin/releases/download/v2.3.0/view-serviceaccount-kubeconfig.yaml)
```

**Comment by superbrothers** [comment]
The PR to krew-index have been merged. You can now upgrade view-serviceaccount-kubeconfig plugin with krew with the following command:

```
kubectl krew upgrade view-serviceaccount-kubeconfig
```
