### ISSUE TITLE
Issue in newer Kubernetes Versions

### ISSUE THREAD

**Issue by joshbinney** [superbrothers/kubectl-view-kubeconfig-plugin#70]
Hey I had this plugin working well on an older cluster, but on newer ones where the service account secrets aren't generated automatically I'm having trouble.

I created a secret for the service account manually as kuberentes team instructs, and that is associated successfully under the service accounts tokens. When I do a get service accounts however, it still says that my service account has 0 secrets, and thats causing the error "Error: serviceaccount mysc has no secrets".

Here is the result of describing the service account:
![image](https://github.com/superbrothers/kubectl-view-serviceaccount-kubeconfig-plugin/assets/48371670/5f879188-bc4e-4c18-9822-58642e1cfc70)

**Comment by superbrothers** [comment]
Please provide the following information:

- Kubernetes Cluster version
- kubectl view-serviceaacount-kubeconfig plugin version

**Comment by superbrothers** [comment]
This issue is closed as it is not active. If you still have issues, please feel free to reopen it.

**Comment by rgeraskin** [comment]
Please reopen, view-serviceaccount-kubeconfig can't handle manually created secrets `type: kubernetes.io/service-account-token` for sa to get a token for kubeconfig

**Comment by Nightreaver** [comment]
@superbrothers 

kube version: v1.25.9
plugin version: view-serviceaccount-kubeconfig  v2.3.1
